import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Import from components
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Burak ASARCIKLI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >

        <div className="min-h-screen flex flex-col relative z-10">
          {/* Include Navbar */}
          <Navbar />
          {/* Main content */}
          <main className="flex-grow mb-10">{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  );
}

